Adds Setup Support
anchore/test-infra pull request #10
Opened 2021-02-02 15:37 UTC by rbrady

This project is currently used in a way where all consuming projects
must git clone this to a tmp directory and copy it to the local
directory.  With python this isn't necessary and we can provide
access to this project in a path by adding it into a project's
requirements-test.txt file.

This patch adds a setup.py file that will copy the ci_harness and
associated task files into the bin of the virtualenv.  With these
files on the path, they no longer require the complexity of make
target "anchore-ci:".  The documentation has been updated to provide
examples of installation and remove references to some of the make
usage no longer needed.

The process of using pip to manage the installation of this project
is served well by using releases/tags.  Because this project does
not change frequently, this is not a difficult or time consuming
process and takes just a moment in the github UI.

Signed-off-by: Ryan Brady <ryan.brady@anchore.com>

2021-02-25 22:00 UTC, alfredodeza approved these changes
@robertp @Btodhunter  this looks good to me and it seems useful...

2021-02-25 22:11 UTC, robertp commented
@alfredodeza @rbrady we have to talk about this, please do not merge

2021-02-26 19:29 UTC, Btodhunter requested changes
I think this is going to be okay to merge as it doesn't force this functionality on our existing CI workflows. The thing that we need to be careful about is that we're using these utility scripts in CI jobs that don't do a `pip install` - such as `make push`.  So we still need to be able to clone the repository for those particular jobs.

We can merge this PR, however I think the README should still include the `anchore-ci` target as that is necessary for the functionality of our current CI pipelines.

2021-02-26 20:12 UTC, alfredodeza commented
> I think this is going to be okay to merge as it doesn't force this functionality on our existing CI workflows. The thing that we need to be careful about is that we're using these utility scripts in CI jobs that don't do a `pip install` - such as `make push`. So we still need to be able to clone the repository for those particular jobs.
> 
> We can merge this PR, however I think the README should still include the `anchore-ci` target as that is necessary for the functionality of our current CI pipelines.

Perhaps that defeats the purpose of this PR then. If we could chat for a few minutes I think we can either clarify and move forward, or see if this isn't worth it and close.

2022-05-16 06:41 UTC, zhill commented
I'm closing this as stale since it's over 1 year old.

2022-05-16 06:41 UTC, closed without merging